[package]
name = "rlox"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
compiler = { path = "../compiler" }
scanner = { path = "../scanner" }
vm = { path = "../vm" }